project:
  type: website

website:
  title: "Customer Segmentation Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Customer_Analysis.ipynb
        text: "Analysis"  
      - href: about.qmd
        text: "About"

format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: true



